import Header from '@/components/Header';
import Head from 'next/head';
import Image from 'next/image';
import { GetStaticProps } from 'next';
import Footer from '../assets/footer.svg';
import Marquee from '@/components/Marquee';
import { Product } from '../product/types';
import IProduct from '@/components/Product';

interface Props {
  products: Product[];
}

export default function Home({ products }: Props) {



  return (
    <>
      <Head>
        <title>Basement</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Marquee />
      <section className='grid lg:grid-cols-3 md:grid-cols-2 container md:gap-8 mt-[103px] mb-[94px]'>
        {products &&
          products.map((prod) => {
            return (
              <IProduct {...prod} key={prod.id}/>
            );
          })}
      </section>
      <Image className='container' src={Footer} alt='Wear Everyday' />
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await import('../product/mock.json');
  const products = res.default;

  return {
    props: {
      products,
    },
  };
};
